### ISSUE TITLE
CI: Test pipeline

### ISSUE THREAD

**Issue by tuxuser** [soupstream/lua-5.1-bigint#2]
Created a basic test pipeline via GH actions: https://github.com/tuxuser/lua-5.1-bigint/blob/ci/tests/.github/workflows/test.yml
Example run: https://github.com/tuxuser/lua-5.1-bigint/actions/runs/2575485665

**Comment by tuxuser** [comment]
Tests now all pass :)

**Comment by soupstream** [comment]
Good idea, thanks! I've merged the PR.
